### ISSUE TITLE
design

### ISSUE THREAD

**Issue by urbels** [doness/iShortener#1]
Hi! nice source you have but why those files difers from http://idvse.com/ ?

**Comment by doness** [comment]
Sorry, I entered the wrong link for the script www.idvse.com demo, maybe I'll upload next time, I will soon fix this demo
demo iShortener is: www.stelso.tk

**Comment by urbels** [comment]
Ohh. Any plans on sharing ivdse code? Looks really nice.

**Comment by doness** [comment]
idvse not ivdse..

yeah ... I will probably be sharing script idvse at the right time

and what do you think about iShortener?
what you like with iShortener?

**Comment by urbels** [comment]
I looked at idvse at first. Just tried a little bit ishortener. For now i'm Using yourls but it has very huge spamers attractivenes.

**Comment by doness** [comment]
wait for the right moment to share the IDVSE, if you wear the YOURLS plugin they provide may block spammers

**Comment by urbels** [comment]
There are plugins, but it`s hard to block spammers anyway, because I need to manually add domains and ip adresses to blacklist. I have fishtank un virustotal plugins to.

**Comment by doness** [comment]
It's pretty cool, your website may be cooler than IDVSE.

**Comment by urbels** [comment]
May be but only in private mode. :D

**Comment by doness** [comment]
:3 why Private mode T_T
hahahaha xD

**Comment by urbels** [comment]
Because in public mode i have 150 spam links a day even with blacklists and spam protection. It just don`t works. :)
